FROM python:3.6
LABEL maintainer 'Lab code'

RUN useradd www && \
    mkdir /app && \
    mkdir /log && \
    chown www /log

USER www
VOLUME /log
WORKDIR /app
EXPOSE 8000

ENTRYPOINT ["/usr/local/bin/python3.6"]
CMD ["run.py"]